### ISSUE TITLE
Dataset query

### ISSUE THREAD

**Issue by mant-ux** [Vini2/MetaCoAG#12]
Hello, do you have time to publish **megahit** based datasets? At present, there are **spades** on the website. Thank you very much!

**Comment by Vini2** [comment]
Hello @mant-ux,

I'm currently testing MetaCoAG on **MEGAHIT** assemblies of all the datasets used in the preprint. I will add them once I have finished testing and let you know.

Thank you for your understanding!

Best regards,
Vijini
