### ISSUE TITLE
Speed up writing final bins

### ISSUE THREAD

**Issue by chassenr** [Vini2/MetaCoAG#4]
Hi @Vini2 ,

thanks for this really great binning tool. It performs very well on my data and it is much faster than other tools (that perform worse). I have a suggestion for the last step in the workflow. I noticed that the awk command to write the fasta files for each bin was taking almost as long as the binning process before... To speed things up, I implemented this step outside of MetaCoAG using bbmap filterbyname and GNU parallel:

```
cd output_dir/bins
ls -1 *.txt | sed 's/\.txt$//' | parallel -j60 'filterbyname.sh in=path/to/contigs.fasta out={}.fasta names={}.txt include=t'
```

Maybe this (or something similar) is also something you may consider for integration?

Thanks!

Cheers,
Christiane

**Comment by Vini2** [comment]
Hello @chassenr,

Thank you very much for your comments. This will be a great way to speed up the final step of writing sequences to fasta files of bins. I will definitely integrate this into the code.

Thank you very much for your suggestion.

Best regards,
Vijini

**Comment by chassenr** [comment]
@Vini2 Thanks a lot for implementing the speed-up. Works perfectly :)

**Comment by Vini2** [comment]
Closing issue after fixing.
