### ISSUE TITLE
Computing abundance TSV

### ISSUE THREAD

**Issue by jdwinkler-lanzatech** [Vini2/MetaCoAG#5]
Hi,

Thanks for your work on this tool, looks very useful. I do have a question about generating the abundance TSV file that is expected; do you have a way of generating that file easily that you recommend? I can probably re-use something from MaxBin2 if not.

**Comment by jdwinkler-lanzatech** [comment]
Ah, figured out a simple way using samtools coverage, so I think I'm set here.

**Comment by mant-ux** [comment]
@jdwinkler-lanzatech 
Hello, how do you get the **abundance tsv** file? I use the script in **concoct**.Input the **bam file** and **contig file** to get the **abundance tsv**, but it is troublesome. Sometimes the error is reported and I don’t know what’s going on. Can you share me your method? thank you very much！

**Comment by JLUVicent** [comment]
Hi, thank you for your question, I have met the same problem, how do you generate abundance tsv files？
I would appreciate it if you could tell me **the detailed steps of generating abundance tsv files** using SamTools
**Thank you!**

**Comment by Vini2** [comment]
Hi @mant-ux and @JLUVicent,

Thank you for pointing this out. I find it easy to use the `contig` option from [CoverM](https://wwood.github.io/CoverM/coverm-contig.html) to get the abundance file. I have updated the README file of MetaCoAG with the code used to generate the abundance .tsv file for a single sample in the section [How to get the abundance.tsv file](https://github.com/Vini2/MetaCoAG/blob/master/README.md#how-to-get-the-abundancetsv-file). You will get the abundance.tsv file in the format explained in [Input Format](https://github.com/Vini2/MetaCoAG/blob/master/README.md#input-format) section and it can be directly used in MetaCoAG.

Hope this helps.

Thank you!
